import { Merriweather, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

// Heading font (h1–h6)
const merriweather = Merriweather({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],   // ← FIXED
  variable: "--font-merriweather",
  display: 'swap',
});

// Body font (p, span, li, etc.)
const openSans = Open_Sans({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${merriweather.variable} ${openSans.variable}`}>
      <body className="antialiased">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}