import { Merriweather, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import ClientBody from "./Components/ClientBody";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-merriweather",
  display: "swap",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-open-sans",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${merriweather.variable} ${openSans.variable}`}
    >
      <body className="antialiased">
        <ClientBody>
          <Navbar />
          {children}
          <Footer />
        </ClientBody>
      </body>
    </html>
  );
}




// import { Merriweather, Open_Sans, Merriweather_Sans } from "next/font/google";
// import "./globals.css";
// import Navbar from "./Components/Navbar";
// import Footer from "./Components/Footer";

// const merriweather = Merriweather({
//   subsets: ["latin"],
//   weight: ["300", "400", "700", "900"],
//   variable: "--font-merriweather",
//   display: "swap",
// });

// const openSans = Open_Sans({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-open-sans",
//   display: "swap",
// });

// const merriweatherSans = Merriweather_Sans({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700", "800"],
//   variable: "--font-merriweather-sans",
//   display: "swap",
// });

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${merriweather.variable} ${openSans.variable} ${merriweatherSans.variable}`}
//     >
//       <body className="antialiased">
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }




